CHANGE_SIZE_MEDIUM = 100
CHANGE_SIZE_LARGE = 300
CHANGE_SIZE_VERY_LARGE = 700
CHANGE_SIZE_MASSIVE = 1500

LARGE_FILE_MEDIUM = 250
LARGE_FILE_LARGE = 500
LARGE_FILE_VERY_LARGE = 1000

SECURITY_FILES_MEDIUM = 1
SECURITY_FILES_HIGH = 3

DATABASE_FILES_MEDIUM = 1
DATABASE_FILES_HIGH = 3

DEPENDENCY_FILES_MEDIUM = 1
DEPENDENCY_FILES_HIGH = 2

CI_FAILURES_MEDIUM = 1
CI_FAILURES_HIGH = 3

TEST_RATIO_LOW = 0.25
TEST_RATIO_MEDIUM = 0.50