"""create push event table

Revision ID: 0679420a34e5
Revises: 55c7b232df18
Create Date: 2026-08-17 17:30:29.415026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0679420a34e5'
down_revision: Union[str, Sequence[str], None] = '55c7b232df18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_event',
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('before_sha', sa.String(length=40), nullable=False),
    sa.Column('after_sha', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('head_commit_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.alter_column('changed_files', 'commit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('changed_files', 'commit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_table('push_event')
    # ### end Alembic commands ###
