"""add PR feature snapshots

Revision ID: 08933e6b772e
Revises: e46601bef160
Create Date: 2026-08-23 16:17:22.568469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08933e6b772e'
down_revision: Union[str, Sequence[str], None] = 'e46601bef160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_feature_snapshot',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changed_files', sa.Integer(), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('unique_authors', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('unique_reviewers', sa.Integer(), nullable=False),
    sa.Column('approvals', sa.Integer(), nullable=False),
    sa.Column('change_requests', sa.Integer(), nullable=False),
    sa.Column('check_count', sa.Integer(), nullable=False),
    sa.Column('successful_checks', sa.Integer(), nullable=False),
    sa.Column('failed_checks', sa.Integer(), nullable=False),
    sa.Column('pending_checks', sa.Integer(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('files_changed_ratio', sa.Float(), nullable=False),
    sa.Column('age_hours', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_feature_snapshot_pull_request_id'), 'pr_feature_snapshot', ['pull_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pr_feature_snapshot_pull_request_id'), table_name='pr_feature_snapshot')
    op.drop_table('pr_feature_snapshot')
    # ### end Alembic commands ###
