"""add revert event tracking

Revision ID: 48848484005f
Revises: 71ed5ebb3254
Create Date: 2026-08-18 10:58:31.217801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48848484005f'
down_revision: Union[str, Sequence[str], None] = '71ed5ebb3254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('changed_files', 'commit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('push_event', 'commit_shas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('push_event', 'commit_shas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('changed_files', 'commit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
