"""add webhook event status

Revision ID: 54ebabefb1cb
Revises: 1088385a3a13
Create Date: 2026-08-10 11:57:48.494781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ebabefb1cb'
down_revision: Union[str, Sequence[str], None] = '1088385a3a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add the column as nullable first
    op.add_column('webhook_event',
        sa.Column('status', sa.String(length=30), nullable=True)
    )

    # Fill existing rows with a default value
    op.execute("UPDATE webhook_event SET status = 'processed'")

    # Alter column to be non-nullable
    op.alter_column('webhook_event', 'status', nullable=False)
    op.add_column('webhook_event', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index('ix_webhook_event_status', 'webhook_event', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_event_status', table_name='webhook_event')
    op.drop_column('webhook_event', 'error_message')
    op.drop_column('webhook_event', 'status')
    # ### end Alembic commands ###
