"""add revert event tracking

Revision ID: 71ed5ebb3254
Revises: b6af308223aa
Create Date: 2026-08-18 10:56:18.871395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71ed5ebb3254'
down_revision: Union[str, Sequence[str], None] = 'b6af308223aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revert_event',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('revert_commit_sha', sa.String(length=40), nullable=False),
    sa.Column('original_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('changed_files', 'commit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('push_event', 'commit_shas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('push_event', 'commit_shas',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('changed_files', 'commit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_table('revert_event')
    # ### end Alembic commands ###
