"""create risk assessment table

Revision ID: 8d5335c5ff8a
Revises: da62e98d2849
Create Date: 2026-08-09 20:50:34.838773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5335c5ff8a'
down_revision: Union[str, Sequence[str], None] = 'da62e98d2849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessment',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessment_pull_request_id', 'risk_assessment', ['pull_request_id'], unique=False)
    op.create_index('ix_risk_assessment_score', 'risk_assessment', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_assessment_score', table_name='risk_assessment')
    op.drop_index('ix_risk_assessment_pull_request_id', table_name='risk_assessment')
    op.drop_table('risk_assessment')
    # ### end Alembic commands ###
