"""create commit table

Revision ID: a81e0cbbf1be
Revises: dcda33d34cee
Create Date: 2026-07-28 10:56:20.433889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81e0cbbf1be'
down_revision: Union[str, Sequence[str], None] = 'dcda33d34cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id', name='uq_repository_github_id'),
    sa.UniqueConstraint('owner', 'name', name='uq_repository_owner_name')
    )
    op.create_index('ix_repository_owner', 'repository', ['owner'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('base_branch', sa.String(length=100), nullable=False),
    sa.Column('head_branch', sa.String(length=100), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_id', name='uq_pull_request_repository_github')
    )
    op.create_index('ix_pull_request_github_id', 'pull_requests', ['github_id'], unique=False)
    op.create_index('ix_pull_request_repository_id', 'pull_requests', ['repository_id'], unique=False)
    op.create_index('ix_pull_request_state', 'pull_requests', ['state'], unique=False)
    op.create_table('commits',
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=150), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha', name='uq_commit_sha')
    )
    op.create_index('ix_commit_pull_request_id', 'commits', ['pull_request_id'], unique=False)
    op.create_index('ix_commit_sha', 'commits', ['sha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commit_sha', table_name='commits')
    op.drop_index('ix_commit_pull_request_id', table_name='commits')
    op.drop_table('commits')
    op.drop_index('ix_pull_request_state', table_name='pull_requests')
    op.drop_index('ix_pull_request_repository_id', table_name='pull_requests')
    op.drop_index('ix_pull_request_github_id', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index('ix_repository_owner', table_name='repository')
    op.drop_table('repository')
    # ### end Alembic commands ###
