"""store pushed commit shas

Revision ID: b6af308223aa
Revises: 0679420a34e5
Create Date: 2026-08-18 10:30:28.095337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6af308223aa'
down_revision: Union[str, Sequence[str], None] = '0679420a34e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('changed_files', 'commit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column("push_event", sa.Column("commit_shas", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_event', 'commit_shas')
    op.alter_column('changed_files', 'commit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
