"""add pull request lifecycle fields

Revision ID: c34b5660a5d9
Revises: 8d5335c5ff8a
Create Date: 2026-08-09 22:31:13.053076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34b5660a5d9'
down_revision: Union[str, Sequence[str], None] = '8d5335c5ff8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add columns as nullable or with defaults
    op.add_column(
        "pull_requests",
        sa.Column("merged", sa.Boolean(), nullable=False, server_default=sa.text("false"))
    )
    op.add_column(
        "pull_requests",
        sa.Column("merged_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "pull_requests",
        sa.Column("closed_at", sa.DateTime(), nullable=True)
    )

    # Step 2: Backfill existing rows explicitly if needed
    # (This ensures all rows have merged = false)
    op.execute("UPDATE pull_requests SET merged = false WHERE merged IS NULL")

    # Step 3: Drop the server default if you don’t want it permanently
    op.alter_column("pull_requests", "merged", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'closed_at')
    op.drop_column('pull_requests', 'merged_at')
    op.drop_column('pull_requests', 'merged')
    # ### end Alembic commands ###
