"""create check run table

Revision ID: da62e98d2849
Revises: e64b2730d00d
Create Date: 2026-08-09 17:47:49.084001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da62e98d2849'
down_revision: Union[str, Sequence[str], None] = 'e64b2730d00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_run',
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conclusion', sa.String(length=50), nullable=True),
    sa.Column('details_url', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id', name='uq_check_run_github_id')
    )
    op.create_index('ix_check_run_conclusion', 'check_run', ['conclusion'], unique=False)
    op.create_index('ix_check_run_pull_request_id', 'check_run', ['pull_request_id'], unique=False)
    op.create_index('ix_check_run_status', 'check_run', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_run_status', table_name='check_run')
    op.drop_index('ix_check_run_pull_request_id', table_name='check_run')
    op.drop_index('ix_check_run_conclusion', table_name='check_run')
    op.drop_table('check_run')
    # ### end Alembic commands ###
