"""Make pull_request_id nullable in commits

Revision ID: e46601bef160
Revises: 198be81c9a35
Create Date: 2026-08-18 13:36:45.146344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46601bef160'
down_revision: Union[str, Sequence[str], None] = '198be81c9a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commits', 'pull_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commits', 'pull_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
