"""create review table

Revision ID: e64b2730d00d
Revises: f2b51204b1fe
Create Date: 2026-08-09 17:37:19.155389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64b2730d00d'
down_revision: Union[str, Sequence[str], None] = 'f2b51204b1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_login', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id', name='uq_review_github_id')
    )
    op.create_index('ix_review_pull_request_id', 'review', ['pull_request_id'], unique=False)
    op.create_index('ix_review_state', 'review', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_state', table_name='review')
    op.drop_index('ix_review_pull_request_id', table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
