"""separate outcome lifecycle and quality

Revision ID: f1c51d31840b
Revises: 582d2893e33a
Create Date: 2026-09-06 20:16:40.726236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c51d31840b'
down_revision: Union[str, Sequence[str], None] = '582d2893e33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_request_outcome', sa.Column('lifecycle_status', sa.String(), nullable=True))
    op.add_column('pull_request_outcome', sa.Column('outcome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_request_outcome', 'outcome')
    op.drop_column('pull_request_outcome', 'lifecycle_status')
    # ### end Alembic commands ###
