"""create pull request table

Revision ID: f6001bb00b8b
Revises: 140baedbcdc2
Create Date: 2026-07-24 21:06:28.414255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6001bb00b8b'
down_revision: Union[str, Sequence[str], None] = '140baedbcdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request',
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('base_branch', sa.String(length=100), nullable=False),
    sa.Column('head_branch', sa.String(length=100), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_id', name='uq_pull_request_repository_github')
    )
    op.create_index('ix_pull_request_github_id', 'pull_request', ['github_id'], unique=False)
    op.create_index('ix_pull_request_repository_id', 'pull_request', ['repository_id'], unique=False)
    op.create_index('ix_pull_request_state', 'pull_request', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pull_request_state', table_name='pull_request')
    op.drop_index('ix_pull_request_repository_id', table_name='pull_request')
    op.drop_index('ix_pull_request_github_id', table_name='pull_request')
    op.drop_table('pull_request')
    # ### end Alembic commands ###
