"""create changed file table

Revision ID: fe394418dd7d
Revises: a81e0cbbf1be
Create Date: 2026-08-07 17:13:45.264577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe394418dd7d'
down_revision: Union[str, Sequence[str], None] = 'a81e0cbbf1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changed_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commit_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('previous_filename', sa.String(length=255), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_changed_file_commit_id', 'changed_files', ['commit_id'], unique=False)
    op.create_index('ix_changed_file_filename', 'changed_files', ['filename'], unique=False)
    op.create_index('ix_changed_file_status', 'changed_files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_changed_file_status', table_name='changed_files')
    op.drop_index('ix_changed_file_filename', table_name='changed_files')
    op.drop_index('ix_changed_file_commit_id', table_name='changed_files')
    op.drop_table('changed_files')
    # ### end Alembic commands ###
